"""Render Astro Galaxy constellation HTML + data-embed for file:// Mission Control."""

from __future__ import annotations

import json
import os
from pathlib import Path
from typing import Any, Dict, Optional


def _repo_root() -> Path:
    env = os.environ.get("GROK_LAB_REPO")
    if env:
        return Path(env).resolve()
    return Path(__file__).resolve().parents[2]


def write_embed(payload: Dict[str, Any], repo: Optional[Path] = None) -> Dict[str, Path]:
    """Write galaxy/data-embed.js + galaxy/latest.json under repo portal/galaxy."""
    root = repo or _repo_root()
    gdir = root / "galaxy"
    gdir.mkdir(parents=True, exist_ok=True)

    latest = gdir / "latest.json"
    embed = gdir / "data-embed.js"
    latest.write_text(json.dumps(payload, indent=2, default=str) + "\n", encoding="utf-8")
    embed.write_text(
        "// generated by lab galaxy collect — do not edit\n"
        "window.GROK_GALAXY = %s;\n" % json.dumps(payload, default=str),
        encoding="utf-8",
    )
    # Ensure index exists
    index = gdir / "index.html"
    if not index.is_file():
        index.write_text(GALAXY_HTML, encoding="utf-8")
    return {"latest": latest, "embed": embed, "index": index}


def ensure_html(repo: Optional[Path] = None) -> Path:
    root = repo or _repo_root()
    gdir = root / "galaxy"
    gdir.mkdir(parents=True, exist_ok=True)
    index = gdir / "index.html"
    index.write_text(GALAXY_HTML, encoding="utf-8")
    return index


# Static constellation UI (Tokyo Night / deep space). Reads window.GROK_GALAXY from embed.
GALAXY_HTML = r"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<title>Astro Galaxy · Grok Star Lab</title>
<script src="data-embed.js"></script>
<style>
  :root {
    --bg: #070b16;
    --panel: #0e1528;
    --line: #243049;
    --text: #e8eefc;
    --muted: #8b9bb8;
    --accent: #7aa2ff;
    --bright: #9ece6a;
    --stable: #7dcfff;
    --dim: #e0af68;
    --dark: #565f89;
    --alert: #f7768e;
  }
  * { box-sizing: border-box; }
  body {
    margin: 0; min-height: 100vh;
    font-family: ui-sans-serif, system-ui, -apple-system, Segoe UI, sans-serif;
    background:
      radial-gradient(1200px 600px at 20% -10%, #1a2744 0%, transparent 55%),
      radial-gradient(900px 500px at 90% 10%, #1b1630 0%, transparent 50%),
      var(--bg);
    color: var(--text);
  }
  header {
    padding: 28px 32px 8px;
    display: flex; flex-wrap: wrap; gap: 12px 24px;
    align-items: baseline; justify-content: space-between;
  }
  h1 { margin: 0; font-size: 1.55rem; letter-spacing: .02em; }
  h1 span { color: var(--accent); font-weight: 600; }
  .sub { color: var(--muted); font-size: .92rem; }
  .score {
    font-variant-numeric: tabular-nums;
    background: var(--panel);
    border: 1px solid var(--line);
    border-radius: 14px;
    padding: 10px 16px;
    min-width: 140px;
  }
  .score .k { font-size: .7rem; text-transform: uppercase; letter-spacing: .08em; color: var(--muted); }
  .score .v { font-size: 1.6rem; margin-top: 2px; }
  main { padding: 8px 32px 40px; display: grid; gap: 20px; }
  .sky {
    position: relative;
    height: 320px;
    border-radius: 18px;
    border: 1px solid var(--line);
    background:
      radial-gradient(circle at 50% 50%, #121a33 0%, #070b16 70%);
    overflow: hidden;
  }
  .star-dot {
    position: absolute;
    border-radius: 50%;
    transform: translate(-50%, -50%);
    box-shadow: 0 0 12px currentColor;
    cursor: default;
    transition: transform .15s ease;
  }
  .star-dot:hover { transform: translate(-50%, -50%) scale(1.25); z-index: 2; }
  .star-dot .label {
    position: absolute; left: 50%; top: calc(100% + 6px);
    transform: translateX(-50%);
    font-size: .68rem; color: var(--muted); white-space: nowrap;
    text-shadow: 0 1px 2px #000;
  }
  .grid {
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(210px, 1fr));
    gap: 12px;
  }
  .card {
    background: var(--panel);
    border: 1px solid var(--line);
    border-radius: 14px;
    padding: 14px 14px 12px;
  }
  .card .top { display: flex; justify-content: space-between; align-items: center; gap: 8px; }
  .card .name { font-weight: 600; text-transform: capitalize; }
  .pill {
    font-size: .68rem; text-transform: uppercase; letter-spacing: .06em;
    padding: 3px 8px; border-radius: 999px; border: 1px solid var(--line);
  }
  .pill.bright { color: var(--bright); border-color: #3d5a2e; background: #142016; }
  .pill.stable { color: var(--stable); border-color: #2a4a5a; background: #101c28; }
  .pill.dim { color: var(--dim); border-color: #5a4520; background: #221a10; }
  .pill.dark { color: var(--dark); }
  .pill.alert { color: var(--alert); border-color: #5a2a36; background: #221018; }
  .mag { margin-top: 10px; height: 6px; background: #1a2238; border-radius: 4px; overflow: hidden; }
  .mag > i { display: block; height: 100%; background: linear-gradient(90deg, var(--accent), #bb9af7); }
  .note { margin-top: 8px; color: var(--muted); font-size: .8rem; min-height: 1.2em; }
  .metrics {
    margin: 8px 0 0; padding: 0; list-style: none;
    font-size: .78rem; color: #b4c0d9; font-variant-numeric: tabular-nums;
  }
  .metrics li { display: flex; justify-content: space-between; gap: 8px; padding: 2px 0; }
  .metrics li span:last-child { color: var(--text); }
  footer {
    padding: 0 32px 28px; color: var(--muted); font-size: .8rem;
  }
  footer a { color: var(--accent); }
  .banner {
    margin: 0 32px; padding: 12px 14px; border-radius: 10px;
    background: #221018; border: 1px solid #5a2a36; color: #ffc0c8;
    display: none;
  }
  .banner.show { display: block; }
</style>
</head>
<body>
  <header>
    <div>
      <h1><span>Astro Galaxy</span> · key data constellation</h1>
      <p class="sub" id="subtitle">Automated tracking &amp; logging for Grok Star Lab</p>
    </div>
    <div class="score">
      <div class="k">Health score</div>
      <div class="v" id="health">—</div>
    </div>
  </header>
  <div class="banner" id="banner"></div>
  <main>
    <div class="sky" id="sky" aria-label="Constellation map"></div>
    <div class="grid" id="cards"></div>
  </main>
  <footer>
    Offline · <code>lab galaxy collect</code> · <code>lab galaxy status</code> ·
    <a href="../dashboard/index.html">Mission Control</a> ·
    <a href="../portal/index.html">Portal</a>
  </footer>
<script>
(function () {
  var G = window.GROK_GALAXY;
  var banner = document.getElementById("banner");
  if (!G || !G.stars) {
    banner.textContent = "No snapshot embedded. Run: lab galaxy collect";
    banner.className = "banner show";
    return;
  }
  document.getElementById("health").textContent =
    (typeof G.health_score === "number" ? G.health_score.toFixed(3) : "—");
  document.getElementById("subtitle").textContent =
    (G.generated_at || "") + " · " + (G.n_stars || 0) + " stars · snapshot " +
    (G.snapshot_id || "—");

  if (G.alerts && G.alerts.length) {
    banner.textContent = "Alerts: " + G.alerts.join(", ");
    banner.className = "banner show";
  }

  var colors = {
    bright: "#9ece6a", stable: "#7dcfff", dim: "#e0af68",
    dark: "#565f89", alert: "#f7768e"
  };
  // Fixed orbital positions (deterministic layout)
  var layout = {
    health: [50, 48], tokens: [22, 35], research: [78, 32],
    session: [50, 18], graph: [30, 68], forge: [70, 70],
    compound: [15, 55], body: [85, 55], resilience: [40, 82],
    showroom: [62, 85]
  };
  var sky = document.getElementById("sky");
  var cards = document.getElementById("cards");
  var names = Object.keys(G.stars).sort();
  names.forEach(function (name) {
    var s = G.stars[name] || {};
    var st = s.status || "dark";
    var mag = typeof s.magnitude === "number" ? s.magnitude : 0;
    var pos = layout[name] || [50, 50];
    var size = 8 + mag * 18;
    var el = document.createElement("div");
    el.className = "star-dot";
    el.style.left = pos[0] + "%";
    el.style.top = pos[1] + "%";
    el.style.width = size + "px";
    el.style.height = size + "px";
    el.style.background = colors[st] || colors.dark;
    el.style.color = colors[st] || colors.dark;
    el.title = name + " · " + st + " · mag " + mag;
    var lab = document.createElement("div");
    lab.className = "label";
    lab.textContent = name;
    el.appendChild(lab);
    sky.appendChild(el);

    var card = document.createElement("div");
    card.className = "card";
    var top = document.createElement("div");
    top.className = "top";
    top.innerHTML = '<div class="name"></div><div class="pill"></div>';
    top.querySelector(".name").textContent = name;
    var pill = top.querySelector(".pill");
    pill.textContent = st;
    pill.className = "pill " + st;
    card.appendChild(top);
    var bar = document.createElement("div");
    bar.className = "mag";
    bar.innerHTML = "<i style=\"width:" + Math.round(mag * 100) + "%\"></i>";
    card.appendChild(bar);
    var note = document.createElement("div");
    note.className = "note";
    note.textContent = s.note || "";
    card.appendChild(note);
    var ul = document.createElement("ul");
    ul.className = "metrics";
    var m = s.metrics || {};
    Object.keys(m).slice(0, 6).forEach(function (k) {
      var li = document.createElement("li");
      var v = m[k];
      if (v !== null && typeof v === "object") v = JSON.stringify(v);
      li.innerHTML = "<span></span><span></span>";
      li.children[0].textContent = k;
      li.children[1].textContent = String(v);
      ul.appendChild(li);
    });
    card.appendChild(ul);
    cards.appendChild(card);
  });
})();
</script>
</body>
</html>
"""
